//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSklad.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public int Id_Client { get; set; }
        public string Name_Client { get; set; }
        public string Address_Client { get; set; }
        public string Number_Client { get; set; }
        public int Sale { get; set; }
    
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
