//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSklad.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooSkladEntities : DbContext
    {
        public ZooSkladEntities()
            : base("name=ZooSkladEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<ORDERS> ORDERS { get; set; }
        public DbSet<PRODUCT> PRODUCT { get; set; }
        public DbSet<УчетныеЗаписи> УчетныеЗаписи { get; set; }
    }
}
