//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooSklad.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public int Id_Product { get; set; }
        public string Name_Product { get; set; }
        public string Type_Product { get; set; }
        public int Amt_on_Sklad { get; set; }
        public int Prodano_za_Month { get; set; }
        public int Amt_Unit { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public int Price { get; set; }
    
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
